// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example_gomicro.proto

package examplePb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyReqMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReqMsg) Reset()         { *m = EmptyReqMsg{} }
func (m *EmptyReqMsg) String() string { return proto.CompactTextString(m) }
func (*EmptyReqMsg) ProtoMessage()    {}
func (*EmptyReqMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_513746092894fc0a, []int{0}
}

func (m *EmptyReqMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReqMsg.Unmarshal(m, b)
}
func (m *EmptyReqMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReqMsg.Marshal(b, m, deterministic)
}
func (m *EmptyReqMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReqMsg.Merge(m, src)
}
func (m *EmptyReqMsg) XXX_Size() int {
	return xxx_messageInfo_EmptyReqMsg.Size(m)
}
func (m *EmptyReqMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReqMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReqMsg proto.InternalMessageInfo

type CommonRespMsg struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonRespMsg) Reset()         { *m = CommonRespMsg{} }
func (m *CommonRespMsg) String() string { return proto.CompactTextString(m) }
func (*CommonRespMsg) ProtoMessage()    {}
func (*CommonRespMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_513746092894fc0a, []int{1}
}

func (m *CommonRespMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRespMsg.Unmarshal(m, b)
}
func (m *CommonRespMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRespMsg.Marshal(b, m, deterministic)
}
func (m *CommonRespMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRespMsg.Merge(m, src)
}
func (m *CommonRespMsg) XXX_Size() int {
	return xxx_messageInfo_CommonRespMsg.Size(m)
}
func (m *CommonRespMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRespMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRespMsg proto.InternalMessageInfo

func (m *CommonRespMsg) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type FooReqMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooReqMsg) Reset()         { *m = FooReqMsg{} }
func (m *FooReqMsg) String() string { return proto.CompactTextString(m) }
func (*FooReqMsg) ProtoMessage()    {}
func (*FooReqMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_513746092894fc0a, []int{2}
}

func (m *FooReqMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooReqMsg.Unmarshal(m, b)
}
func (m *FooReqMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooReqMsg.Marshal(b, m, deterministic)
}
func (m *FooReqMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooReqMsg.Merge(m, src)
}
func (m *FooReqMsg) XXX_Size() int {
	return xxx_messageInfo_FooReqMsg.Size(m)
}
func (m *FooReqMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FooReqMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FooReqMsg proto.InternalMessageInfo

func (m *FooReqMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FooRespMsg struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooRespMsg) Reset()         { *m = FooRespMsg{} }
func (m *FooRespMsg) String() string { return proto.CompactTextString(m) }
func (*FooRespMsg) ProtoMessage()    {}
func (*FooRespMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_513746092894fc0a, []int{3}
}

func (m *FooRespMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooRespMsg.Unmarshal(m, b)
}
func (m *FooRespMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooRespMsg.Marshal(b, m, deterministic)
}
func (m *FooRespMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooRespMsg.Merge(m, src)
}
func (m *FooRespMsg) XXX_Size() int {
	return xxx_messageInfo_FooRespMsg.Size(m)
}
func (m *FooRespMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FooRespMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FooRespMsg proto.InternalMessageInfo

func (m *FooRespMsg) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type BarReqMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BarReqMsg) Reset()         { *m = BarReqMsg{} }
func (m *BarReqMsg) String() string { return proto.CompactTextString(m) }
func (*BarReqMsg) ProtoMessage()    {}
func (*BarReqMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_513746092894fc0a, []int{4}
}

func (m *BarReqMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarReqMsg.Unmarshal(m, b)
}
func (m *BarReqMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarReqMsg.Marshal(b, m, deterministic)
}
func (m *BarReqMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarReqMsg.Merge(m, src)
}
func (m *BarReqMsg) XXX_Size() int {
	return xxx_messageInfo_BarReqMsg.Size(m)
}
func (m *BarReqMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BarReqMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BarReqMsg proto.InternalMessageInfo

func (m *BarReqMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BarRespMsg struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BarRespMsg) Reset()         { *m = BarRespMsg{} }
func (m *BarRespMsg) String() string { return proto.CompactTextString(m) }
func (*BarRespMsg) ProtoMessage()    {}
func (*BarRespMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_513746092894fc0a, []int{5}
}

func (m *BarRespMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarRespMsg.Unmarshal(m, b)
}
func (m *BarRespMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarRespMsg.Marshal(b, m, deterministic)
}
func (m *BarRespMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarRespMsg.Merge(m, src)
}
func (m *BarRespMsg) XXX_Size() int {
	return xxx_messageInfo_BarRespMsg.Size(m)
}
func (m *BarRespMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BarRespMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BarRespMsg proto.InternalMessageInfo

func (m *BarRespMsg) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*EmptyReqMsg)(nil), "EmptyReqMsg")
	proto.RegisterType((*CommonRespMsg)(nil), "CommonRespMsg")
	proto.RegisterType((*FooReqMsg)(nil), "FooReqMsg")
	proto.RegisterType((*FooRespMsg)(nil), "FooRespMsg")
	proto.RegisterType((*BarReqMsg)(nil), "BarReqMsg")
	proto.RegisterType((*BarRespMsg)(nil), "BarRespMsg")
}

func init() { proto.RegisterFile("example_gomicro.proto", fileDescriptor_513746092894fc0a) }

var fileDescriptor_513746092894fc0a = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0xd9, 0x2a, 0xc3, 0xdd, 0xba, 0x81, 0x41, 0x45, 0x2a, 0x0c, 0x09, 0x03, 0x7d, 0x8a,
	0xa0, 0xff, 0xa0, 0xb2, 0xbd, 0x0d, 0x46, 0x7c, 0xf3, 0x45, 0xb2, 0xee, 0x12, 0x02, 0x4b, 0x6f,
	0x4c, 0xa2, 0xd8, 0x7f, 0x2f, 0xa4, 0xa5, 0x56, 0xd0, 0x3d, 0x86, 0x93, 0x7b, 0xf8, 0xbe, 0x03,
	0x97, 0xf8, 0xa5, 0xac, 0x3b, 0xe0, 0x9b, 0x26, 0x6b, 0x2a, 0x4f, 0xc2, 0x79, 0x8a, 0xc4, 0x67,
	0x90, 0xaf, 0xac, 0x8b, 0x8d, 0xc4, 0xf7, 0x4d, 0xd0, 0xfc, 0x0e, 0x66, 0xcf, 0x64, 0x2d, 0xd5,
	0x12, 0x83, 0xdb, 0x04, 0xcd, 0xae, 0x60, 0xe2, 0x31, 0x7c, 0x1c, 0xe2, 0xf5, 0xe8, 0x76, 0x74,
	0x7f, 0x2a, 0xbb, 0x17, 0xbf, 0x81, 0xe9, 0x9a, 0xa8, 0xbd, 0x62, 0x73, 0x18, 0x9b, 0x7d, 0xfa,
	0x90, 0xc9, 0xb1, 0xd9, 0xf3, 0x25, 0x40, 0x0a, 0xff, 0xaa, 0x98, 0x0e, 0x2b, 0x4a, 0xe5, 0xff,
	0xaf, 0x48, 0xe1, 0x51, 0x8a, 0xc7, 0x06, 0xce, 0x57, 0xad, 0x96, 0x74, 0xd5, 0x0b, 0xfa, 0x4f,
	0x53, 0x21, 0x5b, 0xc2, 0xc9, 0xd6, 0xd4, 0x9a, 0x9d, 0x89, 0x81, 0x59, 0x31, 0x17, 0xbf, 0xc5,
	0x16, 0x90, 0xad, 0x89, 0x18, 0x88, 0x5e, 0xa3, 0xc8, 0xc5, 0x80, 0x7a, 0x01, 0x59, 0xa9, 0x3c,
	0x03, 0xd1, 0x33, 0x16, 0xb9, 0xf8, 0x41, 0x2a, 0x2f, 0x5e, 0x99, 0xc6, 0x1a, 0xbd, 0x8a, 0xf8,
	0xd0, 0x4d, 0xbb, 0xdd, 0xed, 0x26, 0x69, 0xd5, 0xa7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29,
	0xec, 0x24, 0x75, 0x6e, 0x01, 0x00, 0x00,
}
